# Generated by Django 4.1.7 on 2023-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_familiar_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
