# Generated by Django 4.1.7 on 2023-06-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_familiar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
